
#复制配置时请根据docker-compose.goSpider.yaml文件中的网络配置和挂载目录，修改对应的IP或创建文件，默认如下
DockerVolume
├── docker-compose.goSpider.yaml
├── goSpider
│   ├── app-config
│   │   └── config.json  #此配置与本项目的app-config/config.json相同
│   ├── hot-data
│   └── logs
│       
├── mongodb-data
│ 
└── redis
    ├── master
    │   ├── conf
    │   │   └── redis.conf
    │   └── data
    │      
    ├── scripts
    │   └── start-node.sh  #此配置与本项目的start-node.sh 相同
    ├── sentinel1
    │   ├── conf
    │   │   └── sentinel.conf
    │   └── data
    ├── sentinel2
    │   ├── conf
    │   │   └── sentinel.conf
    │   └── data
    ├── sentinel3
    │   ├── conf
    │   │   └── sentinel.conf
    │   └── data
    ├── slave1
    │   ├── conf
    │   │   └── redis.conf
    │   └── data
    │     
    └── slave2
        ├── conf
        │   └── redis.conf
        └── data

#--------------------------------------------------------redis.conf-------------------------------------------------------
# 数据节点配置 ,3个节点配置完全相同
# 1. 基础运行配置（补充 bind 和 dir，显式声明更稳妥）
port 6379                  # 容器内Redis实际端口
bind 0.0.0.0               # 允许所有IP访问（数据节点、哨兵）
protected-mode no          # 关闭保护模式（配合bind，双重保障）
daemonize no               # 容器内禁用后台模式（否则启动即退出）
pidfile /var/run/redis.pid # PID文件路径
timeout 0                  # 连接不超时
dir "/data"                # 数据存储目录（必须和挂载的/data对应）
# 2. 密码配置（主从通信、访问安全）
requirepass "123456"       
masterauth "123456"        

# 禁用 RDB 自动保存 避免wsl权限问题
save ""
# 主节点无盘同步（直接传输内存数据，不生成 RDB）
repl-diskless-sync yes
repl-diskless-sync-delay 5
# 从节点无盘加载（接收数据后直接加载到内存，不写临时文件）
repl-diskless-load swapdb

# 3. 数据持久化（依赖dir "/data"，否则失败）
appendonly yes             # 开启AOF持久化
appendfilename "appendonly.aof"
appendfsync everysec       # 每秒同步（平衡性能和数据安全）
# 4. 自动同步核心配置
replicaof localhost 6379   # 触发自动找哨兵要主节点地址
replica-read-only yes      # 从节点只读（主节点自动忽略）
# 5. 同步优化
replica-serve-stale-data yes  # 同步完成前允许提供旧数据
replica-priority 100          # 选举优先级（默认100，数值越小越优先）可自定义



# -----------------------------------------------------------sentinel.conf----------------------------------------------------------
# 哨兵节点配置,3个节点配置完全相同
port 26379
bind 0.0.0.0
protected-mode no
daemonize no
# 核心监控配置（集群名称+初始主节点IP+高仲裁数）
# 注意：初始主节点IP可填任意一个数据节点的固定IP（哨兵启动后会自动发现所有节点）
sentinel monitor mymaster 172.28.0.10 6379 2
# 仲裁数=2（3个哨兵中至少2个确认主节点状态，避免单哨兵误判）
# 认证配置（与数据节点密码一致）
sentinel auth-pass mymaster 123456
# 故障检测与转移配置（防脑裂关键）
sentinel down-after-milliseconds mymaster 5000  # 5秒无响应判定宕机
sentinel failover-timeout mymaster 60000        # 故障转移超时60秒
sentinel parallel-syncs mymaster 1                # 从节点逐个同步新主节点
# 防双主核心配置（所有数据节点都加入哨兵的“已知节点列表”）
# 把3个数据节点的IP:端口都添加到哨兵的known-replica
sentinel known-replica mymaster 172.28.0.10 6379  # 数据节点1
sentinel known-replica mymaster 172.28.0.11 6379  # 数据节点2
sentinel known-replica mymaster 172.28.0.12 6379  # 数据节点3
# 禁止节点上线后立即抢主（防频繁切换）
sentinel master-reboot-down-after-period mymaster 5000  # 上线后5秒内禁止参与选举






